### ISSUE TITLE
Lab Report 5 Feedback

### ISSUE THREAD

**Issue by kheravi** [rdxu1688/cse15l-lab-reports#5]
Here is your feedback for Lab Report 5:

- [x] Explains how tests with different results were found (`diff`, manual search, etc)

Test 1:

- [x] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [x] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Test 2:

- [x] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [x] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Additional comments from your grader:
Your second test should have different results from the other output like you did in test 1. And also show the code that should be fixed as well. Fix those 2 things and you should have a 100%! :)
Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by rdxu1688** [comment]
Hi kheravi, I understand that this is terribly late, I didn't check my email regularly last week due to finals and missed the email regarding the graded lab 5 until now. For my 2nd test, could you please clarify what it means to "have different results from the other output like you did in test 1" means? I'm a little confused since I thought that we could choose tests where both implementations are incorrect as long as we give the "correct" output that differers from both our implementation and theirs. 

I have added a screen shot of the code that should be fixed. Since this is past the deadline, would it still possible to submit a regrade request? 

Thanks,

Richard

**Comment by kheravi** [comment]
You are correct! It is past the deadline for the resubmit but considering I made the mistake and you should've originally gotten the points, you'll be getting a 100%. :)

**Comment by rdxu1688** [comment]
Thank you so much!!
